version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: data_quizz/nestapp:1.0.0
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=quizzs  # Đảm bảo là tên cơ sở dữ liệu chính xác
      - PG_PORT=5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quizzs  # Đảm bảo tên cơ sở dữ liệu trùng với PG_DB trong nestapp
    command: postgres -h 0.0.0.0
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
